# Generated by Django 3.1.3 on 2022-02-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0002_electrical'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Fourth',
            fields=[
                ('Lecturer_Name', models.CharField(max_length=50)),
                ('Lecturer_Id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
