# Generated by Django 3.1.3 on 2022-02-12 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0003_add_fourth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add',
        ),
        migrations.DeleteModel(
            name='Fourth',
        ),
    ]
