# Generated by Django 3.1.3 on 2022-02-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0005_auto_20220212_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electrical_Fourth',
            fields=[
                ('batch', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('Lecturer_Name', models.CharField(max_length=50)),
                ('Lecturer_Code', models.SlugField(max_length=10)),
                ('Lecturer_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Lecturer_Subject', models.CharField(max_length=100)),
                ('Lecturer_Period', models.IntegerField()),
                ('Lab_Class', models.CharField(max_length=10)),
                ('Lab_Period', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Electrical_Second',
            fields=[
                ('batch', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('Lecturer_Name', models.CharField(max_length=50)),
                ('Lecturer_Code', models.SlugField(max_length=10)),
                ('Lecturer_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Lecturer_Subject', models.CharField(max_length=100)),
                ('Lecturer_Period', models.IntegerField()),
                ('Lab_Class', models.CharField(max_length=10)),
                ('Lab_Period', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Electrical_Third',
            fields=[
                ('batch', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('Lecturer_Name', models.CharField(max_length=50)),
                ('Lecturer_Code', models.SlugField(max_length=10)),
                ('Lecturer_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Lecturer_Subject', models.CharField(max_length=100)),
                ('Lecturer_Period', models.IntegerField()),
                ('Lab_Class', models.CharField(max_length=10)),
                ('Lab_Period', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Electrical',
            new_name='Electrical_First',
        ),
    ]
