# Generated by Django 3.1.3 on 2022-02-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0006_auto_20220212_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer_first',
            name='Lecturer_Name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='computer_first',
            name='Lecturer_Period',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='computer_first',
            name='Lecturer_Subject',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='computer_fourth',
            name='Lecturer_Name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='computer_fourth',
            name='Lecturer_Period',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='computer_fourth',
            name='Lecturer_Subject',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='computer_second',
            name='Lecturer_Name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='computer_second',
            name='Lecturer_Period',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='computer_second',
            name='Lecturer_Subject',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
