# Generated by Django 3.1.3 on 2022-02-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0007_auto_20220214_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer_fourth',
            name='Lecturer_Name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='computer_fourth',
            name='Lecturer_Subject',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
