# Generated by Django 3.1.3 on 2022-02-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0009_auto_20220214_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer_first',
            name='Lecturer_Name',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='computer_first',
            name='Lecturer_Subject',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='computer_second',
            name='Lecturer_Name',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='computer_second',
            name='Lecturer_Subject',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='computer_third',
            name='Lecturer_Name',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='computer_third',
            name='Lecturer_Period',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='computer_third',
            name='Lecturer_Subject',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='electrical_first',
            name='Lecturer_Name',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='electrical_first',
            name='Lecturer_Period',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='electrical_first',
            name='Lecturer_Subject',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='electrical_fourth',
            name='Lecturer_Name',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='electrical_fourth',
            name='Lecturer_Period',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='electrical_fourth',
            name='Lecturer_Subject',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='electrical_second',
            name='Lecturer_Name',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='electrical_second',
            name='Lecturer_Period',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='electrical_second',
            name='Lecturer_Subject',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='electrical_third',
            name='Lecturer_Name',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='electrical_third',
            name='Lecturer_Period',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='electrical_third',
            name='Lecturer_Subject',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
