# Generated by Django 3.1.3 on 2022-02-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0011_labroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labroom',
            name='Lab_Name',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='labroom',
            name='Lab_No',
            field=models.IntegerField(default=0),
        ),
    ]
