# Generated by Django 3.1.3 on 2022-02-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0012_auto_20220215_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer_first',
            name='Lab_Class',
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='computer_first',
            name='Lab_Period',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='labroom',
            name='Lab_Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='labroom',
            name='Lab_No',
            field=models.IntegerField(),
        ),
    ]
