# Generated by Django 3.1.3 on 2022-02-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0014_auto_20220215_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer_first',
            name='Lab_Class',
            field=models.CharField(max_length=50),
        ),
    ]
