# Generated by Django 3.1.3 on 2022-02-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0015_auto_20220215_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer_first',
            name='Lab_Period',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='computer_first',
            name='Lecturer_Period',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
