# Generated by Django 3.1.3 on 2022-02-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0022_auto_20220216_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer_fourth',
            name='Lab_Period',
        ),
        migrations.RemoveField(
            model_name='computer_second',
            name='Lab_Period',
        ),
        migrations.RemoveField(
            model_name='computer_third',
            name='Lab_Period',
        ),
        migrations.RemoveField(
            model_name='electrical_first',
            name='Lab_Period',
        ),
        migrations.RemoveField(
            model_name='electrical_fourth',
            name='Lab_Period',
        ),
        migrations.RemoveField(
            model_name='electrical_second',
            name='Lab_Period',
        ),
        migrations.RemoveField(
            model_name='electrical_third',
            name='Lab_Period',
        ),
        migrations.AddField(
            model_name='computer_fourth',
            name='Lab_Lec_Period',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='computer_second',
            name='Lab_Lec_Period',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='computer_third',
            name='Lab_Lec_Period',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='electrical_first',
            name='Lab_Lec_Period',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='electrical_fourth',
            name='Lab_Lec_Period',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='electrical_second',
            name='Lab_Lec_Period',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='electrical_third',
            name='Lab_Lec_Period',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='computer_fourth',
            name='Lab_Class',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='computer_fourth',
            name='Lecturer_Period',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='computer_second',
            name='Lab_Class',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='computer_second',
            name='Lecturer_Period',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='computer_third',
            name='Lab_Class',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='computer_third',
            name='Lecturer_Period',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='electrical_first',
            name='Lab_Class',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='electrical_first',
            name='Lecturer_Period',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='electrical_fourth',
            name='Lab_Class',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='electrical_fourth',
            name='Lecturer_Period',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='electrical_second',
            name='Lab_Class',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='electrical_second',
            name='Lecturer_Period',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='electrical_third',
            name='Lab_Class',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='electrical_third',
            name='Lecturer_Period',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
