# Generated by Django 3.1.3 on 2022-03-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0023_auto_20220216_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer_first',
            name='Lab_Subject',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
