# Generated by Django 3.1.3 on 2022-03-06 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0024_computer_first_lab_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer_first',
            name='Lab_Subject',
        ),
    ]
