# Generated by Django 3.1.3 on 2022-03-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0025_remove_computer_first_lab_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer_first',
            name='Lab_Subject',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='computer_fourth',
            name='Lab_Subject',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='computer_second',
            name='Lab_Subject',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='computer_third',
            name='Lab_Subject',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='electrical_first',
            name='Lab_Subject',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='electrical_fourth',
            name='Lab_Subject',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='electrical_second',
            name='Lab_Subject',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='electrical_third',
            name='Lab_Subject',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
