# Generated by Django 4.1.3 on 2022-11-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0027_civil_first_civil_fourth_civil_second_civil_third'),
    ]

    operations = [
        migrations.CreateModel(
            name='Civil_SecondAB',
            fields=[
                ('batch', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('Lecturer_Name', models.CharField(blank=True, default=None, max_length=50)),
                ('Lecturer_Code', models.SlugField(max_length=10)),
                ('Lecturer_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Lecturer_Subject', models.CharField(blank=True, default=None, max_length=100)),
                ('Lecturer_Period', models.IntegerField(blank=True, default=0, null=True)),
                ('Lab_Class', models.CharField(blank=True, default=None, max_length=50)),
                ('Lab_Subject', models.CharField(blank=True, default=None, max_length=50)),
                ('Lab_Lec_Period', models.CharField(blank=True, default=0, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Civil_SecondCD',
            fields=[
                ('batch', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('Lecturer_Name', models.CharField(blank=True, default=None, max_length=50)),
                ('Lecturer_Code', models.SlugField(max_length=10)),
                ('Lecturer_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Lecturer_Subject', models.CharField(blank=True, default=None, max_length=100)),
                ('Lecturer_Period', models.IntegerField(blank=True, default=0, null=True)),
                ('Lab_Class', models.CharField(blank=True, default=None, max_length=50)),
                ('Lab_Subject', models.CharField(blank=True, default=None, max_length=50)),
                ('Lab_Lec_Period', models.CharField(blank=True, default=0, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Civil_ThirdAB',
            fields=[
                ('batch', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('Lecturer_Name', models.CharField(blank=True, default=None, max_length=50)),
                ('Lecturer_Code', models.SlugField(max_length=10)),
                ('Lecturer_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Lecturer_Subject', models.CharField(blank=True, default=None, max_length=100)),
                ('Lecturer_Period', models.IntegerField(blank=True, default=0, null=True)),
                ('Lab_Class', models.CharField(blank=True, default=None, max_length=50)),
                ('Lab_Subject', models.CharField(blank=True, default=None, max_length=50)),
                ('Lab_Lec_Period', models.CharField(blank=True, default=0, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Civil_ThirdCD',
            fields=[
                ('batch', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('Lecturer_Name', models.CharField(blank=True, default=None, max_length=50)),
                ('Lecturer_Code', models.SlugField(max_length=10)),
                ('Lecturer_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Lecturer_Subject', models.CharField(blank=True, default=None, max_length=100)),
                ('Lecturer_Period', models.IntegerField(blank=True, default=0, null=True)),
                ('Lab_Class', models.CharField(blank=True, default=None, max_length=50)),
                ('Lab_Subject', models.CharField(blank=True, default=None, max_length=50)),
                ('Lab_Lec_Period', models.CharField(blank=True, default=0, max_length=20, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Civil_Fourth',
            new_name='Civil_FirstAB',
        ),
        migrations.RenameModel(
            old_name='Civil_Third',
            new_name='Civil_FirstCD',
        ),
        migrations.RenameModel(
            old_name='Civil_Second',
            new_name='Civil_FourthAB',
        ),
        migrations.RenameModel(
            old_name='Civil_First',
            new_name='Civil_FourthCD',
        ),
    ]
