# Generated by Django 4.1.3 on 2023-02-03 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0028_civil_secondab_civil_secondcd_civil_thirdab_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Civil_FirstAB',
        ),
        migrations.DeleteModel(
            name='Civil_FirstCD',
        ),
        migrations.DeleteModel(
            name='Civil_FourthAB',
        ),
        migrations.DeleteModel(
            name='Civil_FourthCD',
        ),
        migrations.DeleteModel(
            name='Civil_SecondAB',
        ),
        migrations.DeleteModel(
            name='Civil_SecondCD',
        ),
        migrations.DeleteModel(
            name='Civil_ThirdAB',
        ),
        migrations.DeleteModel(
            name='Civil_ThirdCD',
        ),
        migrations.DeleteModel(
            name='Electrical_First',
        ),
        migrations.DeleteModel(
            name='Electrical_Fourth',
        ),
        migrations.DeleteModel(
            name='Electrical_Second',
        ),
        migrations.DeleteModel(
            name='Electrical_Third',
        ),
        migrations.DeleteModel(
            name='Labroom',
        ),
    ]
