# Generated by Django 4.1.3 on 2023-03-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routine", "0029_delete_civil_firstab_delete_civil_firstcd_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Electrical_First",
            fields=[
                ("batch", models.CharField(max_length=20)),
                ("semester", models.CharField(max_length=20)),
                (
                    "Lecturer_Name",
                    models.CharField(blank=True, default=None, max_length=50),
                ),
                ("Lecturer_Code", models.SlugField(max_length=10)),
                ("Lecturer_Id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "Lecturer_Subject",
                    models.CharField(blank=True, default=None, max_length=100),
                ),
                (
                    "Lecturer_Period",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "Lab_Class",
                    models.CharField(blank=True, default=None, max_length=50),
                ),
                (
                    "Lab_Subject",
                    models.CharField(blank=True, default=None, max_length=50),
                ),
                (
                    "Lab_Lec_Period",
                    models.CharField(blank=True, default=0, max_length=20, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Electrical_Fourth",
            fields=[
                ("batch", models.CharField(max_length=20)),
                ("semester", models.CharField(max_length=20)),
                (
                    "Lecturer_Name",
                    models.CharField(blank=True, default=None, max_length=50),
                ),
                ("Lecturer_Code", models.SlugField(max_length=10)),
                ("Lecturer_Id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "Lecturer_Subject",
                    models.CharField(blank=True, default=None, max_length=100),
                ),
                (
                    "Lecturer_Period",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "Lab_Class",
                    models.CharField(blank=True, default=None, max_length=50),
                ),
                (
                    "Lab_Subject",
                    models.CharField(blank=True, default=None, max_length=50),
                ),
                (
                    "Lab_Lec_Period",
                    models.CharField(blank=True, default=0, max_length=20, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Electrical_Second",
            fields=[
                ("batch", models.CharField(max_length=20)),
                ("semester", models.CharField(max_length=20)),
                (
                    "Lecturer_Name",
                    models.CharField(blank=True, default=None, max_length=50),
                ),
                ("Lecturer_Code", models.SlugField(max_length=10)),
                ("Lecturer_Id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "Lecturer_Subject",
                    models.CharField(blank=True, default=None, max_length=100),
                ),
                (
                    "Lecturer_Period",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "Lab_Class",
                    models.CharField(blank=True, default=None, max_length=50),
                ),
                (
                    "Lab_Subject",
                    models.CharField(blank=True, default=None, max_length=50),
                ),
                (
                    "Lab_Lec_Period",
                    models.CharField(blank=True, default=0, max_length=20, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Electrical_Third",
            fields=[
                ("batch", models.CharField(max_length=20)),
                ("semester", models.CharField(max_length=20)),
                (
                    "Lecturer_Name",
                    models.CharField(blank=True, default=None, max_length=50),
                ),
                ("Lecturer_Code", models.SlugField(max_length=10)),
                ("Lecturer_Id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "Lecturer_Subject",
                    models.CharField(blank=True, default=None, max_length=100),
                ),
                (
                    "Lecturer_Period",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "Lab_Class",
                    models.CharField(blank=True, default=None, max_length=50),
                ),
                (
                    "Lab_Subject",
                    models.CharField(blank=True, default=None, max_length=50),
                ),
                (
                    "Lab_Lec_Period",
                    models.CharField(blank=True, default=0, max_length=20, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Labroom",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Lab_Name", models.CharField(max_length=50)),
                ("Lab_No", models.IntegerField()),
            ],
        ),
    ]
